import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portofolio | Gerry Geraldy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#0c0c0c]`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
